<?php declare(strict_types=1);
$labels = ['nombre_razon_social' => 'Nombre o razón social', 'tipo_persona' => 'Tipo de persona', 'rfc' => 'RFC', 'domicilio' => 'Domicilio', 'tipo_servicio' => 'Tipo de servicio', 'tipo_unidad' => 'Tipo de unidades', 'cantidad_unidades' => 'Cantidad de unidades', 'lugar_servicio' => 'Lugar del servicio', 'zona_servicio' => 'Zona o ruta', 'motivo_necesidad' => 'Motivo', 'descripcion_necesidad' => 'Descripción', 'vigencia_observacion' => 'Vigencia solicitada'];
?>
<?= $this->extend('layouts/portal') ?>
<?= $this->section('title') ?>Resumen UR-TT-T-04 - <?= esc($solicitud->folio) ?><?= $this->endSection() ?>
<?= $this->section('content') ?>
<div class="row mb-4"><div class="col"><nav aria-label="breadcrumb"><ol class="breadcrumb small mb-0"><li class="breadcrumb-item"><a href="<?= site_url('/portal/dashboard') ?>">Inicio</a></li><li class="breadcrumb-item"><a href="<?= site_url('/portal/mis-solicitudes') ?>">Mis solicitudes</a></li><li class="breadcrumb-item active">Resumen UR-04</li></ol></nav></div></div>
<div class="card shadow-sm border-0"><div class="card-header bg-primary text-white py-3"><div class="d-flex align-items-center"><div class="bg-white text-primary p-2 rounded-3 me-3"><i class="bi bi-bus-front fs-3"></i></div><div><div class="badge bg-light text-primary mb-1 fw-bold">UR-TT-T-04</div><h1 class="h4 mb-0 text-white">Resumen de solicitud</h1><div class="small opacity-75">Permiso Eventual de Transporte</div></div></div></div><div class="card-body p-3 p-md-4">
<?php if ($solicitud->estatus === 'Pago pendiente'): ?><div class="alert alert-success bg-success bg-opacity-10 border-0"><i class="bi bi-check-circle me-2"></i>La solicitud fue autorizada para pago.</div><?php elseif ($solicitud->estatus === 'Permiso emitido'): ?><div class="alert alert-success bg-success bg-opacity-10 border-0"><i class="bi bi-check-circle me-2"></i>Pago confirmado y permiso eventual emitido.</div><?php else: ?><div class="alert alert-info bg-info bg-opacity-10 border-0"><i class="bi bi-info-circle me-2"></i>Solicitud registrada y enviada a revisión.</div><?php endif; ?>
<div class="row g-3 mb-4"><div class="col-md-6"><div class="border rounded-3 p-3"><div class="small text-muted">Folio</div><div class="font-monospace fw-bold text-primary fs-5"><?= esc($solicitud->folio) ?></div></div></div><div class="col-md-6"><div class="border rounded-3 p-3"><div class="small text-muted">Estado actual</div><span class="badge bg-info text-dark fs-6 mt-1"><?= esc($solicitud->estatus) ?></span></div></div></div>
<h2 class="h5 border-bottom pb-2 text-primary"><i class="bi bi-person-vcard me-2"></i>Datos registrados</h2><dl class="row mb-4"><?php foreach ($labels as $key => $label): ?><?php if (!empty($datos[$key])): ?><dt class="col-md-5 text-muted small pt-1"><?= esc($label) ?></dt><dd class="col-md-7 mb-2"><?= nl2br(esc($datos[$key])) ?></dd><?php endif; ?><?php endforeach; ?></dl><h2 class="h5 border-bottom pb-2 text-primary"><i class="bi bi-file-earmark-check me-2"></i>Documentos adjuntos</h2><div class="list-group mb-4"><?php foreach ($documentos as $documento): ?><div class="list-group-item d-flex justify-content-between align-items-center"><span><i class="bi bi-file-earmark text-primary me-2"></i><?= esc($documento->tipo_documento) ?></span><small class="text-muted text-truncate ms-3"><?= esc($documento->nombre_original) ?></small></div><?php endforeach; ?></div><div class="d-flex flex-wrap gap-2"><?php if ($solicitud->estatus === 'Pago pendiente'): ?><form method="post" action="<?= site_url('/portal/tramites/permiso-eventual/pagar/' . $solicitud->id) ?>"><?= csrf_field() ?><button class="btn btn-success btn-lg" type="submit"><i class="bi bi-cash-coin me-2"></i>Confirmar pago demo</button></form><?php elseif ($solicitud->estatus === 'Permiso emitido'): ?><div class="alert alert-success mb-0"><strong>Referencia:</strong> <?= esc($datos['referencia_pago'] ?? 'MOCK-REF') ?></div><?php endif; ?><a href="<?= site_url('/portal/mis-solicitudes') ?>" class="btn btn-outline-secondary btn-lg">Mis solicitudes</a></div></div></div>
<?= $this->endSection() ?>
