<?php declare(strict_types=1); ?>
<?php $labels = ['nombre_razon_social' => 'Nombre o razón social', 'tipo_persona' => 'Tipo de persona', 'rfc' => 'RFC', 'domicilio' => 'Domicilio', 'tipo_servicio' => 'Tipo de servicio', 'tipo_unidad' => 'Tipo de unidades', 'cantidad_unidades' => 'Cantidad de unidades', 'lugar_servicio' => 'Lugar del servicio', 'zona_servicio' => 'Zona o ruta', 'motivo_necesidad' => 'Motivo', 'descripcion_necesidad' => 'Descripción', 'vigencia_observacion' => 'Vigencia solicitada']; ?>
<?= $this->extend('layouts/portal') ?>
<?= $this->section('content') ?>
<div class="card shadow-sm"><div class="card-header bg-white d-flex justify-content-between align-items-center"><div><div class="small text-muted">Permiso Eventual de Transporte · UR-TT-T-04</div><h1 class="h4 mb-0">Folio: <code><?= esc($solicitud->folio) ?></code></h1></div><span class="badge bg-info text-dark fs-6"><?= esc($solicitud->estatus) ?></span></div><div class="card-body">
    <?php if ($solicitud->estatus === 'Pago pendiente'): ?><div class="alert alert-success">La solicitud fue autorizada para pago en este prototipo.</div><?php elseif ($solicitud->estatus === 'Permiso emitido'): ?><div class="alert alert-success">Pago confirmado y permiso eventual emitido.</div><?php else: ?><div class="alert alert-info">Solicitud registrada. El siguiente paso del prototipo es la revisión documental por parte de Movilidad.</div><?php endif; ?>
    <div class="row g-3 mb-4"><div class="col-md-6"><div class="border rounded p-3"><div class="small text-muted">Fecha de solicitud</div><strong><?= formatear_fecha($solicitud->fecha_solicitud) ?></strong></div></div><div class="col-md-6"><div class="border rounded p-3"><div class="small text-muted">Monto de referencia</div><strong><?= formatear_dinero((float) $solicitud->monto) ?></strong></div></div></div>
    <h2 class="h5 border-bottom pb-2">Datos registrados</h2><dl class="row"><?php foreach ($labels as $key => $label): ?><?php if (!empty($datos[$key])): ?><dt class="col-md-4 text-muted small"><?= esc($label) ?></dt><dd class="col-md-8"><?= nl2br(esc($datos[$key])) ?></dd><?php endif; ?><?php endforeach; ?></dl>
    <h2 class="h5 border-bottom pb-2 mt-4">Documentos adjuntos</h2><ul class="list-group mb-4"><?php foreach ($documentos as $documento): ?><li class="list-group-item d-flex justify-content-between"><span><?= esc($documento->tipo_documento) ?></span><small class="text-muted"><?= esc($documento->nombre_original) ?></small></li><?php endforeach; ?></ul>
    <?php if ($solicitud->estatus === 'Pago pendiente'): ?><form class="d-inline" method="post" action="<?= site_url('/portal/tramites/permiso-eventual/pagar/' . $solicitud->id) ?>"><?= csrf_field() ?><button class="btn btn-success" type="submit"><i class="bi bi-cash-coin me-2"></i>Confirmar pago demo</button></form><?php elseif ($solicitud->estatus === 'Permiso emitido'): ?><div class="alert alert-success mt-3"><strong>Referencia:</strong> <?= esc($datos['referencia_pago'] ?? 'MOCK-REF') ?><br><span class="small">Este permiso puede imprimirse desde el navegador para la demostración.</span></div><?php endif; ?>
    <a href="<?= site_url('/portal/mis-solicitudes') ?>" class="btn btn-primary ms-2">Ver mis solicitudes</a>
</div></div>
<?= $this->endSection() ?>