import { FaltaCatalogo } from "../types/infraccion";

export const CATALOGO_FALTAS_URIANGATO: FaltaCatalogo[] = [
  {
    id: "art-39-ix",
    fundamentoLegal: "Art. 39 Frac. IX",
    descripcion: "No obedecer la señal de alto cuando la luz del semáforo esté en rojo",
    categoria: "MANEJO Y VIALIDAD",
    montoMinUma: 15,
    montoMaxUma: 25,
  },
  {
    id: "art-82-cel",
    fundamentoLegal: "Art. 82",
    descripcion: "Conducir utilizando teléfonos celulares o dispositivos de comunicación móvil",
    categoria: "MANEJO Y VIALIDAD",
    montoMinUma: 10,
    montoMaxUma: 20,
  },
  {
    id: "art-39-iii",
    fundamentoLegal: "Art. 39 Frac. III",
    descripcion: "No respetar los límites de velocidad establecidos en la zona urbana o escolar",
    categoria: "VELOCIDAD",
    montoMinUma: 30,
    montoMaxUma: 50,
  },
  {
    id: "art-95-estac",
    fundamentoLegal: "Art. 95 / Art. 87 Frac. II",
    descripcion: "Estacionarse en lugar prohibido, doble fila o rampas reservadas para personas con discapacidad",
    categoria: "ESTACIONAMIENTO",
    montoMinUma: 10,
    montoMaxUma: 20,
  },
  {
    id: "art-102-casco",
    fundamentoLegal: "Art. 102",
    descripcion: "No portar casco protector certificado el conductor y/o acompañante de motocicleta",
    categoria: "MOTOCICLETAS",
    montoMinUma: 5,
    montoMaxUma: 10,
  },
  {
    id: "art-87-i-placas",
    fundamentoLegal: "Art. 87 Frac. I a)",
    descripcion: "Circular sin placas de circulación, con placas alteradas, ocultas o no visibles",
    categoria: "PLACAS Y REGISTRO",
    montoMinUma: 10,
    montoMaxUma: 15,
  },
  {
    id: "art-39-v-cinturon",
    fundamentoLegal: "Art. 39 Frac. V",
    descripcion: "No utilizar el cinturón de seguridad el conductor y/o acompañantes",
    categoria: "SEGURIDAD PASIVA",
    montoMinUma: 5,
    montoMaxUma: 10,
  },
  {
    id: "art-39-iv-sentido",
    fundamentoLegal: "Art. 39 Frac. IV",
    descripcion: "Circular en sentido opuesto al que indica la vialidad o señalamiento",
    categoria: "MANEJO Y VIALIDAD",
    montoMinUma: 3,
    montoMaxUma: 5,
  },
  {
    id: "art-87-iii-licencia",
    fundamentoLegal: "Art. 87 Frac. III",
    descripcion: "Falta de licencia de conducir para el tipo de vehículo o presentar licencia vencida",
    categoria: "DOCUMENTACIÓN",
    montoMinUma: 5,
    montoMaxUma: 10,
  },
  {
    id: "art-87-iv-tarjeta",
    fundamentoLegal: "Art. 87 Frac. IV",
    descripcion: "Falta de tarjeta de circulación vigente del vehículo",
    categoria: "DOCUMENTACIÓN",
    montoMinUma: 5,
    montoMaxUma: 10,
  },
  {
    id: "art-39-xi-peaton",
    fundamentoLegal: "Art. 39 Frac. XI",
    descripcion: "No respetar el derecho de preferencia de paso a peatones y/o ciclistas en cruces marcados",
    categoria: "PROTECCIÓN PEATONAL",
    montoMinUma: 5,
    montoMaxUma: 10,
  },
  {
    id: "art-115-alcohol",
    fundamentoLegal: "Art. 115",
    descripcion: "Conducir vehículos bajo el influjo de bebidas alcohólicas, drogas o sustancias tóxicas",
    categoria: "SEGURIDAD PÚBLICA",
    montoMinUma: 50,
    montoMaxUma: 100,
  },
  {
    id: "art-39-vii-luces",
    fundamentoLegal: "Art. 39 Frac. VII",
    descripcion: "Circular en horario nocturno o condiciones adversas sin faros delanteros o luces posteriores",
    categoria: "EQUIPAMIENTO",
    montoMinUma: 5,
    montoMaxUma: 10,
  },
  {
    id: "art-39-xxv-puertas",
    fundamentoLegal: "Art. 39 Frac. XXV",
    descripcion: "Circular con puertas abiertas o permitir que pasajeros viajen en estribos",
    categoria: "TRANSPORTE Y PASAJE",
    montoMinUma: 15,
    montoMaxUma: 30,
  },
];
